### ISSUE TITLE
Latest js-ipfs-ceramic pubsub not working?

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ipfs-daemon#18]
I pulled the `latest` image tag this morning from docker hub (`5904b8e93848`) and tried to connect my ceramic daemon to it per usual.

When I start my ceramic daemon, I get:

```> ceramic daemon --ipfs-api http://localhost:5011

(node:30114) UnhandledPromiseRejectionWarning: HTTPError: Pubsub has not started
    at Object.errorHandler [as handleError] (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/ipfs-http-client/src/lib/core.js:76:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Client.fetch (/Users/jonathanschwartz/Documents/daemon-land/js-sdk/services/api/node_modules/ipfs-utils/src/http.js:140:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by v-stickykeys** [comment]
Thanks for reporting @Schwartz10 this should be resolved with #19 . Image is likely in progress rn and should be built in a few minutes.
